dict_result_table = {'ring': '№ кольца',
                     'date_of_capture_in_season': 'Дата отлова в сезон',
                     'date_of_tagging': 'Дата мечения',
                     'returns': 'Возвраты',
                     'date_of_return': 'Дата возврата',
                     'date_of_death': 'Дата гибели',
                     'genus': 'Род',
                     'species': 'Вид',
                     'gender': 'Пол',
                     'age_EURING': 'Возраст EURING',
                     'age': 'Возвраст',
                     'pneumatization': '% пневматизации',
                     'richness': 'Балл жирности',
                     'muscle': 'Балл мышцы',
                     'weight': 'Вес',
                     'beak_from_forehead': 'Клюв от лба',
                     'beak_from_nostril': 'Клюв от ноздри',
                     'wing_min': 'Крыло min',
                     'wing_max': 'Крыло max',
                     'tarsus': 'Цевка',
                     'tail': 'Хвост',
                     'head_length': 'Длина головы',
                     'mesh_number': '№ сетки',
                     'biotope_code': 'Код биотопа',
                     'mesh_footage': 'Метраж сетей',
                     'check_time': 'Время проверки',
                     'place_of_tagging': 'Место мечения',
                     'latitude_of_tagging': 'Широта мечения',
                     'longitude_of_tagging': 'Долгота мечения',
                     'molting_stage': 'Стадия линьки'}
